### ISSUE TITLE
码表缺字（偏旁、部首、笔划）

### ISSUE THREAD

**Issue by CNMan** [yanhuacuo/98wubi-unicode#1]
```
U+2E9F,⺟
U+2EF3,⻳
U+9FDD,鿝
```

从aab更改为agnb是不是合理？
```
U+26B00,𦬀
```

建议删除tfbw，仅保留tfwb
```
U+2068F,𠚏
```

建议删除jupe,仅保留opfe
```
U+2B387,𫎇
```

超集98单义表.txt 第33427行一头雾水
```
is	it
```

**Comment by yanhuacuo** [comment]
谢谢指正，码表初校，还有很多地方要更正

**Comment by CNMan** [comment]
@yanhuacuo https://github.com/CNMan/UnicodeCJK-WuBi/commit/a967f73a02862311cf003e18f55eb7cec63f40b4
最近的码表CJK、CJK-A区新增了很多“容错码”，有些确实很别扭

**Comment by yanhuacuo** [comment]
98五笔的超集扩编人员在字形和发布字体上有分歧，添加容错是为暂时搁置争议，集中力量先将unicode已发布的全部汉字编完，这个事已经做完了。

下一阶段，osfans （98五笔用户） 打算建立在线 WIKI ，以便进行更进一步的细审和校对。同时等待更可靠的国标规范或商业字体，最终解决容错码的问题。

**Comment by CNMan** [comment]
国标字形和Unicode的G源字形有些不一致；单一字体或多或少也有错误字形
https://github.com/program-in-chinese/wubi_code_editor
同时显示15个字体的字形，边校对字形，边校对五笔编码
```
BabelStoneHan\
FZKaiS\方正楷体S
FZKaiT\方正楷体T
FZNewKaiS\方正新楷体S
FZSongS\方正宋体S
HanaMin\花園明朝
HYFangSong\汉仪仿宋
HYZiDianSong\汉仪字典宋
MingLiU\細明體
MingLiU_HKSCS\細明體_HKSCS
NotoSansMonoCJKSC\
SimSun\中易宋体
TW-Kai\全字庫正楷體
TW-Sung\全字庫正宋體
ZhongHuaSong\中华书局宋体
```

![](https://user-images.githubusercontent.com/8692234/69428996-84460880-0d6d-11ea-8f62-04023bb6e996.png)
